# ------------------
# DATABASE SETTINGS
# ------------------
database:
  # The location of the SQLite database file relative to the project root.
  path: "data/news_sentiment.db"
  # The location of the SQL file that defines the table schema.
  schema: "src/database/schema.sql"

# ------------------
# LOGGING SETTINGS
# ------------------
logging:
  # The location of the log file.
  path: "data/logs/pipeline.log"
  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"

# ------------------
# SCRAPER SETTINGS
# ------------------
scraper:
  # A user-agent to make our scraper look like a real browser.
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  
  # URLs for the news sources
  sources:
    finviz: "https://finviz.com/news.ashx"
    yahoo: "https://finance.yahoo.com/news/"

  # Settings specific to the Yahoo (Selenium) scraper
  yahoo_scraper:
    # Number of times to scroll down the page to load more articles.
    scroll_count: 3
    # Time to wait (in seconds) between scrolls for new articles to load.
    scroll_delay: 2