# ==========================
# DATABASE SETTINGS
# ==========================
database:
  path: "data/news_sentiment.db"
  schema: "src/database/schema.sql"

# ==========================
# LOGGING SETTINGS
# ==========================
logging:
  path: "data/logs/pipeline.log"
  level: "INFO"

# ==========================
# SCRAPER SETTINGS
# ==========================
scraper:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"

  # URLs for our two reliable, static news sources
  sources:
    barchart: "https://www.barchart.com/news/stocks"
    seeking_alpha: "https://seekingalpha.com/market-news"